checkbox/pmr-configs

pmr.conf

This is a small tool for caching revisions and results, would like to add to our pmr.conf

Add revcache to pmr.conf

---

pmr-noncert.conf

Signed-off-by: Maciej Kisielewski <maciej.kisielewski@canonical.com>

add chelmsford to the non-cert conf

---

pmr-noncert.conf

Add denver to PMR non-cert list.

Add denver

---

pmr-noncert.conf

Please help to add project - limerick into auto-merge.
Thank U :-)

Add limerick

---

pmr.conf

This adds the cert-appliances project.

add cert-appliances project

---

pmr-noncert.conf

Add Staunton project

---

pmr.conf

Add lp:denver

---

pmr-noncert.conf

Add Baoshan project

---

pmr-noncert.conf

add shiner project

---

pmr-noncert.conf

Add lp:conroe for Conroe project.

Add lp:conroe

---

pmr.conf

Add lp:cc-lab-manager

---

pmr-noncert.conf

Please help to add Sugarland project
Thank you

Add sugarland project

---

pmr-noncert.conf

Add config for project reading

Add config for project reading

---

pmr-noncert.conf

add project katy into PMR config

Add project katy into PMR config

---

pmr-noncert.conf

Add project kariya into PMR conf

Add kariya project

---

pmr-noncert.conf

add project tillamook into PMR config

Add tillamook project

---

pmr-noncert.conf

add project rochester into PRM config

Add project rochester into PRM config

---

pmr-noncert.conf

Add project jollyville into PRM config
Signed-off-by: ChunAn <an.wu@canonical.com>

Add project jollyville into PRM config

---

pmr-noncert.conf

add project Murcia into PMR config

Add project murcia into PMR config

---

pmr-noncert.conf

Add project baytown into PMR config

Add project baytown into PMR config

---

pmr-noncert.conf

Signed-off-by: Laider Lai <laider.lai@canonical.com>

Add project erlangen into PMR config

---

pmr-noncert.conf

Add project austin-charlotte into PMR config

Add project austin-charlotte into PMR config
